# Generated by Django 5.2.1 on 2025-06-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomendasmodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='encomendas_imagens/'),
        ),
    ]
